---
version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - lopopolo
    labels:
      - A-deps
  - package-ecosystem: cargo
    directory: "/fuzz"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - lopopolo
    labels:
      - A-deps
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - lopopolo
    labels:
      - A-deps
