[package]
name = "bubblebabble"
version = "2.0.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"
description = "Rust implementation of the Bubble Babble binary data encoding"
repository = "https://github.com/artichoke/bubblebabble"
readme = "README.md"
license = "MIT"
keywords = ["encoding", "bubblebabble"]
categories = ["encoding"]

[dependencies]
