[package]
name = "boba"
version = "4.0.0" # remember to set `html_root_url` in `src/lib.rs`.
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
license = "MIT"
edition = "2018"
readme = "README.md"
repository = "https://github.com/artichoke/boba"
documentation = "https://docs.rs/boba"
homepage = "https://github.com/artichoke/boba"
description = "Encoder and decoder for the Bubble Babble binary data encoding"
keywords = ["encode", "decode", "utf8", "bubblebabble"]
categories = ["encoding"]
include = [
  "src/**/*.rs",
  "LICENSE",
  "README.md",
]

[features]
default = ["std"]
# Enable dependency on the Rust standard library.
#
# This feature exists to support the possiblity that `boba` may
# eventually support compiling in `no_std` environments.
#
# Currently, this feature is required to build `boba`.
std = []

[dependencies]
bstr = { version = "0.2", default-features = false }

[dev-dependencies]
bubblebabble = "0.1"
version-sync = "0.9"
