version: 2.1
orbs:
  win: circleci/windows@2.1.0
commands:
  setup-linux-builder:
    description: Setup Artichoke Linux builder image
    steps:
      - run:
          name: Install Rust Toolchain
          command: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y -q --profile minimal --default-toolchain "$(cat rust-toolchain)"
            echo 'export "PATH"="$HOME/.cargo/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Installed Toolchain Versions
          command: |
            rustc --version --verbose
            cargo --version --verbose
  setup-linux-linter:
    description: Setup Artichoke Linux linter image
    steps:
      - setup-linux-builder
      - run:
          name: Install Rust Toolchain
          command: |
            rustup component add rustfmt
            rustup component add clippy
      - run:
          name: Installed Toolchain Versions
          command: |
            rustc --version --verbose
            cargo --version --verbose
            rustfmt --version
            cargo clippy -- --version
jobs:
  x86_64-linux:
    docker:
      - image: debian:buster
    resource_class: large
    steps:
      - checkout
      - setup-linux-builder
      - run:
          name: Build Workspace
          command: |
            cargo build
          environment:
            RUST_BACKTRACE: 1
      - run:
          name: Test Workspace
          command: |
            cargo test --all-features
          environment:
            RUST_BACKTRACE: 1
  linter:
    docker:
      - image: debian:buster
    resource_class: large
    steps:
      - checkout
      - setup-linux-linter
      - run:
          name: rustfmt
          command: |
            cargo fmt -- --check --color=auto
      - run:
          name: clippy
          command: |
            cargo clippy -- -D warnings
      - run:
          name: doc
          command: |
            cargo doc
      - persist_to_workspace:
          root: target
          paths:
            - "doc"
  deploy:
    docker:
      - image: node:lts
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ac:59:ea:b4:7f:14:dd:de:a7:50:3e:d0:35:c9:a5:a9"
      - attach_workspace:
          at: target
      - run: npm install -g gh-pages@2.1.1
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            gh-pages \
              --user "ci-build <ci-build@hyperbo.la>" \
              --message "[skip ci] build docs" \
              --dist target/doc
workflows:
  version: 2
  build:
    jobs:
      - x86_64-linux
      - linter
      - deploy:
          requires:
            - x86_64-linux
            - linter
          filters:
            branches:
              only: master
