---
name: Merge
"on":
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  labels:
    name: Labels
    runs-on: ubuntu-24.04
    permissions:
      issues: write # required to read and write labels
      pull-requests: write # required to read and write labels

    steps:
      - uses: mheap/github-action-required-labels@23e10fde7e062233401931a0eece796cd9bf3177 # v5.6.0
        with:
          mode: exactly
          count: 0
          labels: "S-do-not-merge, S-wip"
