name: Fuzz
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * TUE"
jobs:
  encode:
    name: Fuzz encode
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: Fuzz
        run: cargo fuzz run encode -- -max_total_time=90

  decode:
    name: Fuzz decode
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: Fuzz
        run: cargo fuzz run decode -- -max_total_time=90

  roundtrip:
    name: Fuzz encode/decode roundtrip
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: Fuzz
        run: cargo fuzz run roundtrip -- -max_total_time=90
