---
name: Fuzz
"on":
  schedule:
    - cron: "0 9 * * *"
permissions: {}
jobs:
  encode:
    name: Fuzz encode
    runs-on: ubuntu-24.04
    env:
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install nightly Rust toolchain
        run: |
          rustup set profile minimal
          rustup toolchain install nightly --no-self-update
          rustup default nightly

      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: Fuzz
        run: cargo fuzz run encode -- -max_total_time=1800 # 30 minutes

  decode:
    name: Fuzz decode
    runs-on: ubuntu-24.04
    env:
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install nightly Rust toolchain
        run: |
          rustup set profile minimal
          rustup toolchain install nightly --no-self-update
          rustup default nightly

      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: Fuzz
        run: cargo fuzz run decode -- -max_total_time=1800 # 30 minutes

  roundtrip:
    name: Fuzz encode/decode roundtrip
    runs-on: ubuntu-24.04
    env:
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install nightly Rust toolchain
        run: |
          rustup set profile minimal
          rustup toolchain install nightly --no-self-update
          rustup default nightly

      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: Fuzz
        run: cargo fuzz run roundtrip -- -max_total_time=1800 # 30 minutes
