---
name: Fuzz
"on":
  schedule:
    - cron: "0 9 * * *"
jobs:
  encode:
    name: Fuzz encode
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.6.0

      - name: Install Rust toolchain
        uses: artichoke/setup-rust/build-and-test@v1.10.0
        with:
          toolchain: nightly

      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: Fuzz
        run: cargo fuzz run encode -- -max_total_time=1800 # 30 minutes

  decode:
    name: Fuzz decode
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.6.0

      - name: Install Rust toolchain
        uses: artichoke/setup-rust/build-and-test@v1.10.0
        with:
          toolchain: nightly

      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: Fuzz
        run: cargo fuzz run decode -- -max_total_time=1800 # 30 minutes

  roundtrip:
    name: Fuzz encode/decode roundtrip
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.6.0

      - name: Install Rust toolchain
        uses: artichoke/setup-rust/build-and-test@v1.10.0
        with:
          toolchain: nightly

      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: Fuzz
        run: cargo fuzz run roundtrip -- -max_total_time=1800 # 30 minutes
